### PR TITLE
added .editorconfig and added logic to set/check data(groupType)

### PR DESCRIPTION
**Pull request by reubenmoes**

### CODE REVIEW

**Comment by nathanshubert** [comment]
Do you think this project really needs an `. editorconfig`? I feel like since this is a one-file project that will always be used in a larger project where style is dictated, it could be left out here.

**Comment by reubenmoes** [comment]
I think `.editorconfig` makes sense. I never clone this repo directly in a project.  I just download the .js file.  
But I can remove it if you don't want it.

**Comment by nathanshubert** [comment]
Yeah, I'd rather leave it out since A) panelGroup.js is useless outside of a larger project where an .editorconfig is likely to exist, and B) I'd rather use `indent_size = 4` than 2 as that's my preferred style when not required my a framework to do otherwise.

**Comment by reubenmoes** [comment]
removed

**Comment by reubenmoes** [comment]
ok to merge?

**Pull request merged**
